package com.mcserver.launcher.ui.theme
import androidx.compose.ui.graphics.Color

object McColors {
    val Primary = Color(0xFF00C6A0)
    val PrimaryVariant = Color(0xFF009B7D)
    val OnPrimary = Color(0xFF00382C)
    val PrimaryContainer = Color(0xFF005544)
    val OnPrimaryContainer = Color(0xFF7FFFD4)
    val Secondary = Color(0xFF7C8BB8)
    val OnSecondary = Color(0xFF111B3A)
    val SecondaryContainer = Color(0xFF2D3A5C)
    val Background = Color(0xFF0A0E17)
    val OnBackground = Color(0xFFE2E5EC)
    val Surface = Color(0xFF131722)
    val OnSurface = Color(0xFFE2E5EC)
    val SurfaceVariant = Color(0xFF1E2333)
    val OnSurfaceVariant = Color(0xFF9DA4B8)
    val SurfaceDim = Color(0xFF080B12)
    val Outline = Color(0xFF3D4358)
    val OutlineVariant = Color(0xFF252A3A)
    val Error = Color(0xFFFF5370)
    val ErrorContainer = Color(0xFF93001E)
    val OnErrorContainer = Color(0xFFFFDAD6)
    val Success = Color(0xFF66DE7B)
    val SuccessContainer = Color(0xFF00531A)
    val OnSuccessContainer = Color(0xFFA2F5AD)
    val Warning = Color(0xFFFFB74D)
    val WarningContainer = Color(0xFF5D3A00)
    val Online = Color(0xFF66DE7B)
    val Offline = Color(0xFF5C6178)
    val Accent = Color(0xFF00E5FF)
    val AccentContainer = Color(0xFF004D5A)
}

// ── Compatibility aliases for existing code ──
object LightColors {
    val Primary get() = McColors.Primary
    val OnPrimary get() = McColors.OnPrimary
    val PrimaryContainer get() = McColors.PrimaryContainer
    val OnPrimaryContainer get() = McColors.OnPrimaryContainer
    val Secondary get() = McColors.Secondary
    val OnSecondary get() = McColors.OnSecondary
    val SecondaryContainer get() = McColors.SecondaryContainer
    val OnSecondaryContainer = Color(0xFF1D192B)
    val Tertiary = Color(0xFF7D5260)
    val OnTertiary = Color.White
    val TertiaryContainer = Color(0xFFFFD8E4)
    val OnTertiaryContainer = Color(0xFF31111D)
    val Background get() = McColors.Background
    val OnBackground get() = McColors.OnBackground
    val Surface get() = McColors.Surface
    val OnSurface get() = McColors.OnSurface
    val SurfaceVariant get() = McColors.SurfaceVariant
    val OnSurfaceVariant get() = McColors.OnSurfaceVariant
    val SurfaceDim get() = McColors.SurfaceDim
    val Outline get() = McColors.Outline
    val OutlineVariant get() = McColors.OutlineVariant
    val Error get() = McColors.Error
    val OnError = Color.White
    val ErrorContainer get() = McColors.ErrorContainer
    val OnErrorContainer get() = McColors.OnErrorContainer
    val Success get() = McColors.Success
    val OnSuccess = Color.Black
    val SuccessContainer get() = McColors.SuccessContainer
    val OnSuccessContainer get() = McColors.OnSuccessContainer
    val Warning get() = McColors.Warning
    val OnWarning = Color.Black
    val WarningContainer get() = McColors.WarningContainer
    val OnWarningContainer = Color(0xFFFFE08A)
    val Info get() = McColors.Accent
    val OnInfo = Color.Black
    val InfoContainer get() = McColors.AccentContainer
    val OnInfoContainer = Color(0xFFC7E7FF)
    val Online get() = McColors.Online
    val Offline get() = McColors.Offline
}

object DarkColors {
    val Primary get() = McColors.Primary
    val OnPrimary get() = McColors.OnPrimary
    val PrimaryContainer get() = McColors.PrimaryContainer
    val OnPrimaryContainer get() = McColors.OnPrimaryContainer
    val Secondary get() = McColors.Secondary
    val OnSecondary get() = McColors.OnSecondary
    val SecondaryContainer get() = McColors.SecondaryContainer
    val OnSecondaryContainer get() = McColors.OnPrimaryContainer
    val Tertiary = Color(0xFFEFB8C8)
    val OnTertiary = Color(0xFF492532)
    val TertiaryContainer = Color(0xFF633B48)
    val OnTertiaryContainer = Color(0xFFFFD8E4)
    val Background get() = McColors.Background
    val OnBackground get() = McColors.OnBackground
    val Surface get() = McColors.Surface
    val OnSurface get() = McColors.OnSurface
    val SurfaceVariant get() = McColors.SurfaceVariant
    val OnSurfaceVariant get() = McColors.OnSurfaceVariant
    val SurfaceDim get() = McColors.SurfaceDim
    val Outline get() = McColors.Outline
    val OutlineVariant get() = McColors.OutlineVariant
    val Error get() = McColors.Error
    val OnError = Color(0xFF601410)
    val ErrorContainer get() = McColors.ErrorContainer
    val OnErrorContainer get() = McColors.OnErrorContainer
    val Success get() = McColors.Success
    val OnSuccess = Color(0xFF063500)
    val SuccessContainer get() = McColors.SuccessContainer
    val OnSuccessContainer get() = McColors.OnSuccessContainer
    val Warning get() = McColors.Warning
    val OnWarning = Color(0xFF3D2E00)
    val WarningContainer get() = McColors.WarningContainer
    val OnWarningContainer = Color(0xFFFFE08A)
    val Info get() = McColors.Accent
    val OnInfo = Color(0xFF003352)
    val InfoContainer get() = McColors.AccentContainer
    val OnInfoContainer = Color(0xFFC7E7FF)
    val Online get() = McColors.Online
    val Offline get() = McColors.Offline
}

object AmoledColors {
    val Primary get() = McColors.Primary
    val OnPrimary = Color.Black
    val PrimaryContainer get() = McColors.PrimaryContainer
    val OnPrimaryContainer get() = McColors.OnPrimaryContainer
    val Secondary get() = McColors.Secondary
    val OnSecondary = Color.Black
    val SecondaryContainer = Color(0xFF2A2438)
    val OnSecondaryContainer get() = McColors.OnPrimaryContainer
    val Tertiary = Color(0xFFEFB8C8)
    val OnTertiary = Color.Black
    val TertiaryContainer = Color(0xFF3A2530)
    val OnTertiaryContainer = Color(0xFFFFD8E4)
    val Background = Color.Black
    val OnBackground get() = McColors.OnBackground
    val Surface = Color(0xFF0A0A0A)
    val OnSurface get() = McColors.OnSurface
    val SurfaceVariant = Color(0xFF1A1A2E)
    val OnSurfaceVariant get() = McColors.OnSurfaceVariant
    val SurfaceDim = Color.Black
    val Outline = Color(0xFF333333)
    val OutlineVariant = Color(0xFF222222)
    val Error get() = McColors.Error
    val OnError = Color.Black
    val ErrorContainer get() = McColors.ErrorContainer
    val OnErrorContainer get() = McColors.OnErrorContainer
    val Success get() = McColors.Success
    val OnSuccess = Color.Black
    val SuccessContainer get() = McColors.SuccessContainer
    val OnSuccessContainer get() = McColors.OnSuccessContainer
    val Warning get() = McColors.Warning
    val OnWarning = Color.Black
    val WarningContainer get() = McColors.WarningContainer
    val OnWarningContainer = Color(0xFFFFE08A)
    val Info get() = McColors.Accent
    val OnInfo = Color.Black
    val InfoContainer get() = McColors.AccentContainer
    val OnInfoContainer = Color(0xFFC7E7FF)
    val Online get() = McColors.Online
    val Offline = Color(0xFF333333)
}
